version: '2'
services:
    hexo:
        container_name: hexo
        build: ./hexo
        image: ender74/hexo
        entrypoint: /bin/true
    server:
        container_name: thg-server
        image: ender74/hexo
        ports: 
            - "4000:4000"
        command: "server"
        volumes: 
            - "../:/site"        
        depends_on:
            - hexo
    build:
        container_name: thg-server
        image: ender74/hexo
        command: "generate"
        volumes:
            - "../:/site"
        depends_on:
            - hexo
